"""Self-contained localhost control-panel page."""

CONTROL_PANEL_HTML = r"""<!doctype html>
<html lang="zh-CN" data-ui-version="2">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>文明 6 工作流助手</title>
<style>
:root{color-scheme:dark;--bg:#071018;--panel:rgba(13,25,36,.94);--panel2:#111f2c;--soft:#0b1721;--line:#263949;--line2:#1b2c38;--text:#eef4f7;--muted:#91a4b2;--gold:#d8b55f;--gold2:#f3d17d;--green:#58c994;--red:#f1747d;--blue:#67aee8;--shadow:0 18px 55px rgba(0,0,0,.24)}
*{box-sizing:border-box}html{min-width:320px;background:var(--bg)}body{margin:0;min-height:100vh;color:var(--text);font:14px/1.5 Inter,"Segoe UI","Microsoft YaHei",sans-serif;background:radial-gradient(circle at 82% -10%,rgba(45,92,126,.4),transparent 34%),radial-gradient(circle at 10% 18%,rgba(96,76,35,.18),transparent 26%),linear-gradient(180deg,#09141e 0,var(--bg) 46%,#050c12 100%)}button,input{font:inherit}button:focus-visible,input:focus-visible{outline:2px solid var(--gold2);outline-offset:2px}.shell{width:min(1480px,100%);margin:auto;padding:22px}.topbar{display:flex;justify-content:space-between;align-items:center;gap:18px;margin-bottom:18px}.brand{display:flex;align-items:center;gap:13px;min-width:0}.crest{display:grid;place-items:center;width:48px;height:48px;flex:0 0 auto;border:1px solid #7f682f;border-radius:14px;color:#19150c;background:linear-gradient(145deg,#f0d485,#b88c37);font:700 21px Georgia,serif}.brand small{display:block;color:var(--gold);letter-spacing:.18em;font-weight:700}.brand h1{margin:2px 0 0;font:500 25px/1.15 Georgia,"Microsoft YaHei",serif}.brand p{margin:3px 0 0;color:var(--muted);font-size:12px}.actions{display:flex;flex-wrap:wrap;justify-content:flex-end;gap:9px}.btn{min-height:38px;border:1px solid var(--line);border-radius:9px;padding:8px 13px;color:var(--text);background:#142432;cursor:pointer;transition:.15s}.btn:hover:not(:disabled){border-color:#537084;transform:translateY(-1px)}.btn.primary{color:#17130b;border-color:#e4c371;background:linear-gradient(180deg,#e4c56f,#b98d39);font-weight:750}.btn.danger{color:#ffc3c7;border-color:#6d3940;background:#29171b}.btn:disabled{opacity:.48;cursor:not-allowed;transform:none}.toggle{display:inline-flex;align-items:center;gap:7px;color:var(--muted);font-size:12px}.toggle input{accent-color:var(--gold)}
.status{display:grid;grid-template-columns:repeat(6,minmax(0,1fr));gap:10px;margin-bottom:16px}.stat{min-width:0;padding:12px 14px;border:1px solid var(--line);border-radius:11px;background:rgba(13,25,36,.88)}.stat label{display:block;color:var(--muted);font-size:11px;margin-bottom:4px}.stat strong{display:block;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;font-size:15px}.dot{display:inline-block;width:8px;height:8px;margin-right:7px;border-radius:50%;background:var(--red)}.dot.ok{background:var(--green);box-shadow:0 0 12px rgba(88,201,148,.55)}
.workspace{display:grid;grid-template-columns:minmax(0,1.45fr) minmax(320px,.75fr);gap:16px}.stack{display:grid;align-content:start;gap:16px;min-width:0}.card{min-width:0;overflow:hidden;border:1px solid var(--line);border-radius:13px;background:var(--panel);box-shadow:var(--shadow)}.card.attention{border-color:#735f2e;background:linear-gradient(180deg,rgba(66,51,22,.38),rgba(13,25,36,.94))}.head{display:flex;align-items:center;justify-content:space-between;gap:12px;padding:13px 15px;border-bottom:1px solid var(--line);background:rgba(17,31,44,.78)}.head h2{margin:0;font-size:14px;letter-spacing:.035em}.head p{margin:2px 0 0;color:var(--muted);font-size:11px}.body{padding:14px 15px}.badge{display:inline-flex;align-items:center;gap:5px;max-width:100%;border:1px solid #385061;border-radius:999px;padding:2px 8px;color:#c0ced7;font-size:11px;white-space:nowrap}.badge.good,.badge.done,.badge.ready{color:#85ddb2;border-color:#356b52}.badge.warn,.badge.awaiting_confirmation{color:var(--gold2);border-color:#786231}.badge.bad,.badge.failed,.badge.blocked,.badge.escalated,.badge.uncertain{color:#ff9ca3;border-color:#734149}
.flow{display:grid;grid-template-columns:repeat(6,minmax(0,1fr));gap:8px;margin-bottom:14px}.step{position:relative;min-width:0;text-align:center;color:var(--muted)}.step:not(:last-child)::after{content:"";position:absolute;top:13px;left:calc(50% + 15px);right:calc(-50% + 15px);height:1px;background:var(--line)}.step.done:not(:last-child)::after{background:#597548}.mark{position:relative;z-index:1;display:grid;place-items:center;width:27px;height:27px;margin:0 auto 6px;border:1px solid var(--line);border-radius:50%;background:var(--soft);font-size:11px}.step.done .mark{color:#173222;border-color:#6ca36f;background:#79bd7c}.step.active .mark{color:#17130b;border-color:#f0d17f;background:var(--gold);box-shadow:0 0 0 4px rgba(216,181,95,.13)}.step.active{color:var(--text)}.step span:last-child{display:block;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;font-size:11px}.summary{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:9px}.metric{padding:10px;border:1px solid var(--line2);border-radius:9px;background:var(--soft)}.metric label{display:block;color:var(--muted);font-size:10px}.metric b{display:block;margin-top:3px;overflow-wrap:anywhere}.metrics{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:9px}
.row{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:12px;padding:12px 0;border-bottom:1px solid var(--line2)}.row:last-child{border-bottom:0}.row.event{grid-template-columns:1fr}.row-title{font-weight:700;overflow-wrap:anywhere}.row-meta{margin-top:4px;color:var(--muted);font-size:11px;overflow-wrap:anywhere}.row-detail{margin-top:7px;color:#c8d3da;overflow-wrap:anywhere}.row-actions{display:flex;flex-wrap:wrap;align-items:center;justify-content:flex-end;gap:7px}.event-top{display:flex;justify-content:space-between;gap:10px}.empty{padding:20px 8px;color:var(--muted);text-align:center}.notice{margin-bottom:14px;padding:11px 13px;border-left:3px solid var(--blue);border-radius:5px;background:#102333;color:#cfe5f4}.notice.error{border-left-color:var(--red);background:#2a171b;color:#ffc1c5}.notice.success{border-left-color:var(--green);background:#10251d;color:#a8e5c7}.block+.block{margin-top:12px}.json{max-height:310px;overflow:auto;margin:0;padding:11px;border:1px solid var(--line2);border-radius:9px;background:#071018;color:#b9c8d2;font:11px/1.55 ui-monospace,SFMono-Regular,Consolas,monospace;white-space:pre-wrap;word-break:break-word}.footer{padding:17px 4px 4px;color:#667985;text-align:center;font-size:11px}
@media(max-width:1120px){.status{grid-template-columns:repeat(3,minmax(0,1fr))}.workspace{grid-template-columns:1fr}}@media(max-width:720px){.shell{padding:14px}.topbar{align-items:flex-start;flex-direction:column}.actions{justify-content:flex-start;width:100%}.status{grid-template-columns:repeat(2,minmax(0,1fr))}.flow{grid-template-columns:repeat(3,minmax(0,1fr);row-gap:13px}.step::after{display:none}.summary{grid-template-columns:repeat(2,minmax(0,1fr))}.row{grid-template-columns:1fr}.row-actions{justify-content:flex-start}}
</style>
</head>
<body><main class="shell">
<header class="topbar"><div class="brand"><div class="crest" aria-hidden="true">VI</div><div><small>CIVILIZATION VI</small><h1>本地工作流控制台</h1><p>观察游戏状态、批准关键动作，并安全地单步推进自动化。</p></div></div><div class="actions"><label class="toggle"><input id="autoRefresh" type="checkbox" checked>自动刷新</label><button class="btn" id="plannerBtn" type="button">测试规划器</button><button class="btn" id="refreshBtn" type="button">刷新</button><button class="btn primary" id="tickBtn" type="button">运行一次 Tick</button></div></header>
<section class="status" aria-label="运行状态"><div class="stat"><label>游戏连接</label><strong id="gameStatus"><span class="dot"></span>未观测</strong></div><div class="stat"><label>当前回合</label><strong id="turn">—</strong></div><div class="stat"><label>Runtime 状态</label><strong id="runtime">—</strong></div><div class="stat"><label>执行模式</label><strong id="mode">—</strong></div><div class="stat"><label>自动结束回合</label><strong id="autoEnd">—</strong></div><div class="stat"><label>规划器</label><strong id="plannerStatus">—</strong></div></section>
<div id="notice" aria-live="polite"></div>
<section class="workspace"><div class="stack">
<article class="card"><div class="head"><div><h2>当前工作流</h2><p>动作发送与结果验证分属不同 Tick。</p></div><span class="badge" id="lastOutcome">尚无结果</span></div><div class="body"><div class="flow" id="workflow"></div><div class="summary" id="tickSummary"></div></div></article>
<article class="card attention"><div class="head"><div><h2>需要你处理</h2><p>只显示当前状态允许的人工操作。</p></div><span class="badge warn" id="humanActionCount">0</span></div><div class="body" id="humanActions"></div></article>
<article class="card"><div class="head"><div><h2>任务队列</h2><p>最近 24 个 TurnAction 节点。</p></div><span class="badge" id="taskCount">0</span></div><div class="body" id="tasks"></div></article>
</div><aside class="stack">
<article class="card"><div class="head"><div><h2>阻塞与事件</h2><p>按严重级别排序的开放事件。</p></div><span class="badge" id="eventCount">0</span></div><div class="body" id="events"></div></article>
<article class="card"><div class="head"><div><h2>规划器连接</h2><p>凭证只保存在本地后端。</p></div></div><div class="body" id="planner"></div></article>
<article class="card"><div class="head"><div><h2>最近 Tick 指标</h2><p>状态查询、规划、发送与验证。</p></div></div><div class="body" id="metrics"></div></article>
<article class="card"><div class="head"><div><h2>最近一次结果</h2><p>持久化的兼容 Tick envelope。</p></div></div><div class="body"><pre class="json" id="lastTick">尚无 Tick 结果</pre></div></article>
</aside></section><footer class="footer">仅监听 127.0.0.1 · 页面不能绕过审批、执行锁、动作白名单或后置验证</footer>
</main><script>
const token=new URLSearchParams(location.search).get('token')||'';const el=id=>document.getElementById(id);const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));const ui={busy:false,auto:true};
const runtimeNames={OBSERVING:'观察中',ROUTING:'路由中',PLANNING:'规划中',PLANNER_BACKOFF:'规划器退避',AWAITING_APPROVAL:'等待动作确认',AWAITING_HUMAN:'等待人工处理',ACTION_SENT:'动作已发送',RECONCILING:'验证中',TURN_TRANSITIONING:'结束回合中',SYSTEM_ERROR:'系统错误',PAUSED:'已暂停'};const outcomeNames={MUTATION_SENT:'动作已发送',ATTEMPT_RECONCILED:'动作验证完成',TURN_TRANSITION_STARTED:'已发送结束回合',TURN_TRANSITION_CONFIRMED:'回合推进已确认',AWAITING_HUMAN:'等待人工处理',AWAITING_APPROVAL:'等待动作确认',NO_SAFE_ACTION:'当前没有安全动作',LOGICAL_PLANNER_REQUEST_CREATED:'已创建规划请求',STRATEGIC_PROPOSAL_READY:'战略提案待审批',MISSION_GRAPH_PATCHED:'Mission 已修复'};
async function api(path,opts={}){const r=await fetch(path,{...opts,headers:{'X-Civ6-Token':token,'Content-Type':'application/json',...(opts.headers||{})}});const d=await r.json().catch(()=>({error:`HTTP ${r.status}`}));if(!r.ok)throw new Error(d.error||d.reason||`HTTP ${r.status}`);return d}
function metric(name,value,suffix=''){return `<div class="metric"><label>${esc(name)}</label><b>${esc(value??'—')}${esc(suffix)}</b></div>`}function badge(status){const css=['done','ready'].includes(status)?'good':status==='awaiting_confirmation'?'warn':['failed','blocked','escalated','uncertain'].includes(status)?'bad':'';return `<span class="badge ${css} ${esc(status)}">${esc(status)}</span>`}
function flowIndex(d){const s=d.human_actions?.runtime_state||'',o=d.last_tick?.workflow_tick?.outcome||d.last_tick?.outcome||'';if(o==='TURN_TRANSITION_CONFIRMED')return 5;if(s==='TURN_TRANSITIONING'||o==='TURN_TRANSITION_STARTED')return 4;if(['ACTION_SENT','RECONCILING'].includes(s)||['MUTATION_SENT','ATTEMPT_RECONCILED'].includes(o))return 3;if(['AWAITING_APPROVAL','AWAITING_HUMAN'].includes(s))return 2;if(['PLANNING','PLANNER_BACKOFF'].includes(s)||o.includes('PLANNER')||o.includes('PROPOSAL'))return 1;return 0}
function renderFlow(d){const steps=['观测','规划','人工确认','执行与验证','结束回合','下一回合'],active=flowIndex(d);el('workflow').innerHTML=steps.map((x,i)=>`<div class="step ${i<active?'done':i===active?'active':''}"><span class="mark">${i<active?'✓':i+1}</span><span>${esc(x)}</span></div>`).join('');const o=d.last_tick?.workflow_tick?.outcome||d.last_tick?.outcome||'尚无结果';el('lastOutcome').textContent=outcomeNames[o]||o;el('tickSummary').innerHTML=[metric('Tick ID',d.last_tick?.tick_id||'—'),metric('结果',outcomeNames[o]||o),metric('本 Tick 写操作',d.last_tick?.metrics?.mutation_count??'—'),metric('是否暂停',d.last_tick?.paused?'是':'否')].join('')}
function humanButton(label,action,game,target,danger=false){return `<button type="button" class="btn ${danger?'danger':''}" data-human-action="${esc(action)}" data-game-id="${esc(game)}" data-target-id="${esc(target)}">${esc(label)}</button>`}function row(title,detail,buttons,meta=''){return `<div class="row"><div><div class="row-title">${esc(title)}</div>${meta?`<div class="row-meta">${esc(meta)}</div>`:''}<div class="row-detail">${esc(detail)}</div></div><div class="row-actions">${buttons}</div></div>`}
function renderHuman(d){const h=d.human_actions||{},g=d.game?.game_id||'',rows=[];if(h.runtime_state==='AWAITING_HUMAN'){const p=h.strategic_proposal;if(p){const m=p.research_mission||{},target=m.desired_outcome?.technology||m.objective||'研究战略';rows.push(row(`研究提案：${target}`,(p.strategic_objectives||[]).join('；')||h.human_wait?.blocking_reason||'战略提案需要明确决定。',humanButton('批准提案','approve-proposal',g,p.proposal_id)+humanButton('拒绝','reject-proposal',g,p.proposal_id,true),`Contract 基线 revision ${p.expected_base_revision}`))}else rows.push(row('工作流等待人工复核',h.human_wait?.blocking_reason||'下一 Tick 会重新读取游戏状态。',humanButton('确认并重新评估','resume',g,g)))}for(const t of d.waiting_tasks||[])rows.push(row(`动作确认：${t.action_type}`,t.reason||t.task_id,humanButton('批准动作','confirm-task',g,t.task_id)+humanButton('取消动作','reject-task',g,t.task_id,true),`${t.entity_type}:${t.entity_id} · 回合 ${t.due_turn}`));for(const a of h.retryable_attempts||[])rows.push(row(`安全重试：${a.action_type}`,a.reason||'该 Attempt 已证明没有提交。',humanButton('重新入队','retry-attempt',g,a.action_attempt_id),a.action_attempt_id));el('humanActionCount').textContent=rows.length;el('humanActions').innerHTML=rows.length?rows.join(''):'<div class="empty">当前没有需要人工处理的事项。</div>'}
function renderTasks(d){const tasks=(d.tasks||[]).slice().reverse().slice(0,24);el('taskCount').textContent=d.tasks?.length||0;el('tasks').innerHTML=tasks.length?tasks.map(t=>`<div class="row"><div><div class="row-title">${esc(t.action_type)} · ${esc(t.entity_type)}:${esc(t.entity_id)}</div><div class="row-meta">${esc(t.task_id)} · 目标回合 ${esc(t.due_turn)}</div><div class="row-detail">${esc(t.reason||'')}</div></div><div>${badge(t.status)}</div></div>`).join(''):'<div class="empty">尚无 TurnAction 记录。</div>'}
function renderEvents(d){const events=d.open_events||[];el('eventCount').textContent=events.length;el('events').innerHTML=events.length?events.map(e=>{const msg=e.payload?.message||e.payload?.reason||JSON.stringify(e.payload||{}),css=e.blocking?'bad':e.level>=2?'warn':'';return `<div class="row event"><div class="event-top"><div class="row-title">${esc(e.event_type)}</div><span class="badge ${css}">L${esc(e.level)} · ${e.blocking?'阻塞':'提示'}</span></div><div class="row-detail">${esc(msg)}</div><div class="row-meta">回合 ${esc(e.last_seen_turn??e.turn)} · 已出现 ${esc(e.seen_count||1)} 次</div></div>`}).join(''):'<div class="empty">当前没有开放事件。</div>'}
function renderPlanner(d){const c=d.planner_connection||{},p=d.last_planner_probe,x=d.planner_diagnostics||d.latest_agent?.transport,blocks=[];blocks.push(`<div class="block metrics">${metric('后端',c.backend||'—')}${metric('模型',c.model||'—')}${metric('凭证',c.credential_present===false?'缺失':c.configured?'已配置':'待配置')}${metric('浏览器可见密钥',c.secret_exposed_to_browser?'是':'否')}</div>`);if(p){blocks.push(`<div class="block metrics">${metric('连接测试',p.ok?'成功':'失败')}${metric('HTTP',p.http_status||'—')}${metric('耗时',p.duration_seconds??'—',p.duration_seconds==null?'':'s')}${metric('Request ID',p.request_id||'—')}</div>`);if(p.error)blocks.push(`<div class="notice error block">${esc(p.error)}</div>`)}if(x)blocks.push(`<div class="block metrics">${metric('HTTP 尝试',x.attempt_count??'—')}${metric('响应头',x.connect_and_headers_seconds??'—','s')}${metric('首字节',x.first_byte_seconds??'—','s')}${metric('完整响应',x.completion_seconds??'—','s')}</div>`);if(d.planner_backoff?.until_epoch)blocks.push(`<div class="notice error block">规划器正在退避：${esc(d.planner_backoff.category||'transient_provider_failure')}，延迟 ${esc(d.planner_backoff.delay_seconds||'—')} 秒。</div>`);el('planner').innerHTML=blocks.join('');el('plannerStatus').innerHTML=p?.ok?'<span class="dot ok"></span>已连接':c.configured?'<span class="dot"></span>待测试':'<span class="dot"></span>未配置';el('plannerBtn').textContent=p?.ok?'重新测试规划器':'测试规划器'}
function renderMetrics(d){const m=d.latest_metrics;el('metrics').innerHTML=m?`<div class="metrics">${metric('总耗时',m.total_seconds,'s')}${metric('状态读取',m.state_query_seconds,'s')}${metric('规划耗时',m.agent_seconds,'s')}${metric('动作发送',m.mutation_delivery_seconds,'s')}${metric('验证耗时',m.verification_seconds,'s')}${metric('MCP 调用',m.mcp_call_count)}${metric('规划尝试',m.agent_attempt_count??m.agent_call_count)}${metric('只读查询',m.information_query_count??0)}</div>`:'<div class="empty">尚无 Tick 指标。</div>'}
function notice(msg='',kind=''){el('notice').innerHTML=msg?`<div class="notice ${esc(kind)}">${esc(msg)}</div>`:''}function render(d){el('gameStatus').innerHTML=d.game?.observed?'<span class="dot ok"></span>已观测':'<span class="dot"></span>未观测';el('turn').textContent=d.game?.turn??'—';const s=d.human_actions?.runtime_state||(d.server?.tick_running?'RUNNING':'OBSERVING');el('runtime').textContent=d.server?.tick_running?'Tick 执行中':runtimeNames[s]||s||'空闲';el('mode').textContent=d.config?.execution_mode||'—';el('autoEnd').textContent=d.config?.auto_end_turn?'开启':'关闭';el('tickBtn').disabled=!!(d.server?.tick_running||ui.busy);renderFlow(d);renderHuman(d);renderTasks(d);renderEvents(d);renderPlanner(d);renderMetrics(d);el('lastTick').textContent=d.last_tick?JSON.stringify(d.last_tick,null,2):'尚无 Tick 结果';if(d.server?.last_error)notice(d.server.last_error,'error')}
async function refresh(quiet=false){if(!token){notice('URL 缺少本地访问令牌。请通过启动脚本打开浏览器，或复制终端输出的完整地址。','error');return}try{const d=await api('/api/state');render(d);if(!quiet&&!d.server?.last_error)notice('状态已刷新。','success')}catch(e){notice(e.message,'error')}}async function busy(button,label,fn){if(ui.busy)return;ui.busy=true;const old=button.textContent;button.disabled=true;button.textContent=label;try{await fn()}catch(e){notice(e.message,'error')}finally{ui.busy=false;button.disabled=false;button.textContent=old;await refresh(true)}}
async function runTick(){await busy(el('tickBtn'),'执行中…',async()=>{const r=await api('/api/tick',{method:'POST',body:'{}'}),o=r.result?.workflow_tick?.outcome||r.result?.outcome||'Tick 已完成';notice(outcomeNames[o]||o,'success')})}async function probe(){await busy(el('plannerBtn'),'连接中…',async()=>{const r=await api('/api/planner/probe',{method:'POST',body:'{}'});notice(r.result?.ok?'规划器连接测试成功。':'规划器连接测试失败。',r.result?.ok?'success':'error')})}
async function human(button){const a=button.dataset.humanAction,g=button.dataset.gameId,t=button.dataset.targetId,paths={resume:`/api/games/${encodeURIComponent(g)}/workflow/resume`,'approve-proposal':`/api/games/${encodeURIComponent(g)}/proposals/${encodeURIComponent(t)}/approve`,'reject-proposal':`/api/games/${encodeURIComponent(g)}/proposals/${encodeURIComponent(t)}/reject`,'confirm-task':`/api/games/${encodeURIComponent(g)}/tasks/${encodeURIComponent(t)}/confirm`,'reject-task':`/api/games/${encodeURIComponent(g)}/tasks/${encodeURIComponent(t)}/reject`,'retry-attempt':`/api/games/${encodeURIComponent(g)}/attempts/${encodeURIComponent(t)}/retry`};if(!paths[a])return;await busy(button,'处理中…',async()=>{const r=await api(paths[a],{method:'POST',body:'{}'});notice(r.reason||'操作已记录。','success');if(a==='resume'){await api('/api/tick',{method:'POST',body:'{}'});notice('恢复请求已记录，并完成一次重新评估 Tick。','success')}})}
el('refreshBtn').addEventListener('click',()=>refresh());el('tickBtn').addEventListener('click',runTick);el('plannerBtn').addEventListener('click',probe);el('autoRefresh').addEventListener('change',e=>ui.auto=e.target.checked);document.addEventListener('click',e=>{const b=e.target.closest('[data-human-action]');if(b)human(b)});document.addEventListener('visibilitychange',()=>{if(!document.hidden&&ui.auto)refresh(true)});refresh(true);setInterval(()=>{if(ui.auto&&!ui.busy&&!document.hidden)refresh(true)},2500);
</script></body></html>"""
